/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/bXEEf3I1GJp1oEhU/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#464646"]} />
      <group {...props} dispose={null}>
        <group name="Room2" position={[101, 277.38, 100]}>
          <group name="hand_1" position={[54.59, -46.78, -102.54]}>
            <group name="hand_forearm_g" position={[0, -22.57, -17.87]}>
              <group
                name="hand_palm_g"
                position={[0, 45.85, 21.96]}
                rotation={[-0.47, 0, 0]}
              >
                <mesh
                  name="hand_1_finger_8"
                  geometry={nodes.hand_1_finger_8.geometry}
                  material={materials.piano_key_white}
                  castShadow
                  receiveShadow
                  position={[-3.47, 0.79, 16.28]}
                  rotation={[-1.14, 0.05, -0.07]}
                  scale={[1, 0.71, 1]}
                />
                <mesh
                  name="hand_1_finger_7"
                  geometry={nodes.hand_1_finger_7.geometry}
                  material={materials.piano_key_white}
                  castShadow
                  receiveShadow
                  position={[3.11, -0.61, 7.43]}
                  rotation={[-0.99, 0.05, 0.21]}
                  scale={[1, 0.71, 1]}
                />
                <mesh
                  name="hand_1_finger_6"
                  geometry={nodes.hand_1_finger_6.geometry}
                  material={materials.piano_key_white}
                  castShadow
                  receiveShadow
                  position={[0.08, 0.65, 7.91]}
                  rotation={[-1.24, 0.04, 0.1]}
                  scale={[1, 0.71, 1]}
                />
                <mesh
                  name="hand_1_finger_5"
                  geometry={nodes.hand_1_finger_5.geometry}
                  material={materials.piano_key_white}
                  castShadow
                  receiveShadow
                  position={[-5.05, 0.35, -0.69]}
                  rotation={[-Math.PI / 2, 0, -0.44]}
                  scale={[1, 1.09, 1]}
                />
                <mesh
                  name="hand_1_finger_4"
                  geometry={nodes.hand_1_finger_4.geometry}
                  material={materials.piano_key_white}
                  castShadow
                  receiveShadow
                  position={[-2.95, 1.74, 2.54]}
                  rotation={[-1.56, 0, -0.17]}
                  scale={[1, 0.84, 1]}
                />
                <mesh
                  name="hand_1_finger_3"
                  geometry={nodes.hand_1_finger_3.geometry}
                  material={materials.piano_key_white}
                  castShadow
                  receiveShadow
                  position={[-0.43, 1.61, 3.16]}
                  rotation={[-1.43, 0.01, 0.11]}
                  scale={[1, 0.84, 1]}
                />
                <mesh
                  name="hand_1_finger_2"
                  geometry={nodes.hand_1_finger_2.geometry}
                  material={materials.piano_key_white}
                  castShadow
                  receiveShadow
                  position={[5.05, -0.21, 1.84]}
                  rotation={[-1.43, 0.03, 0.48]}
                />
                <mesh
                  name="hand_1_finger_1"
                  geometry={nodes.hand_1_finger_1.geometry}
                  material={materials.piano_key_white}
                  castShadow
                  receiveShadow
                  position={[1.94, 1.03, 2.79]}
                  rotation={[-1.34, 0.05, 0.23]}
                />
                <mesh
                  name="hand_1_palm"
                  geometry={nodes.hand_1_palm.geometry}
                  material={materials.piano_key_white}
                  castShadow
                  receiveShadow
                  position={[-0.37, 0.33, -4.5]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
              </group>
              <mesh
                name="hand_1_wrist"
                geometry={nodes.hand_1_wrist.geometry}
                material={materials.tv}
                castShadow
                receiveShadow
                position={[0.04, 13.94, -3.56]}
                rotation={[-0.91, 0, 0]}
              />
              <mesh
                name="hand_1_forearm"
                geometry={nodes.hand_1_forearm.geometry}
                material={materials.piano_key_white}
                castShadow
                receiveShadow
                position={[0.04, -9.18, -15.51]}
                rotation={[-1.37, 0, 0]}
              />
            </group>
            <mesh
              name="hand_1_base"
              geometry={nodes.hand_1_base.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[0.15, -24.34, -17.96]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="table_room_2" position={[10.23, -113.51, -137.31]}>
            <mesh
              name="table_room_2_cube_11"
              geometry={nodes.table_room_2_cube_11.geometry}
              material={materials["table_room_2_cube_11 Material"]}
              castShadow
              receiveShadow
              position={[-39.73, 31.02, 34.31]}
            />
            <mesh
              name="table_room_2_cube_10"
              geometry={nodes.table_room_2_cube_10.geometry}
              material={materials["table_room_2_cube_10 Material"]}
              castShadow
              receiveShadow
              position={[-39.73, 8.33, 34.31]}
            />
            <mesh
              name="table_room_2_cube_9"
              geometry={nodes.table_room_2_cube_9.geometry}
              material={materials["table_room_2_cube_9 Material"]}
              castShadow
              receiveShadow
              position={[-39.73, -14.37, 34.31]}
            />
            <mesh
              name="table_room_2_cube_8"
              geometry={nodes.table_room_2_cube_8.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-40.45, -22.09, 14.15]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1, 1.45, 1]}
            />
            <mesh
              name="table_room_2_cube_7"
              geometry={nodes.table_room_2_cube_7.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-40.45, 0.58, 14.15]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1, 1.45, 1]}
            />
            <mesh
              name="table_room_2_cube_6"
              geometry={nodes.table_room_2_cube_6.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-40.45, 23.26, 14.15]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1, 1.45, 1]}
            />
            <mesh
              name="table_room_2_cube_5"
              geometry={nodes.table_room_2_cube_5.geometry}
              material={materials[" closet_1"]}
              castShadow
              receiveShadow
              position={[0, 37.44, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="table_room_2_cube_4"
              geometry={nodes.table_room_2_cube_4.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-62.43, -2.42, -31.45]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="table_room_2_cube_3"
              geometry={nodes.table_room_2_cube_3.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[62.16, -2.42, -31.45]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="table_room_2_cube_2"
              geometry={nodes.table_room_2_cube_2.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-62.29, -36.81, 30.94]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="table_room_2_cube_1"
              geometry={nodes.table_room_2_cube_1.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[62.16, -2.42, 30.94]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="safe_1" position={[-151.5, 47.6, 111.21]}>
            <group name="safe_1_door_g" position={[17.8, -0.12, -23.81]}>
              <mesh
                name="safe_1_door"
                geometry={nodes.safe_1_door.geometry}
                material={materials.road}
                castShadow
                receiveShadow
                position={[-0.61, 0, 0]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              />
              <mesh
                name="safe_1_rect_9"
                geometry={nodes.safe_1_rect_9.geometry}
                material={materials["safe_1_rect_9 Material"]}
                castShadow
                receiveShadow
                position={[1.7, -2.57, 8.53]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                name="safe_1_rect_8"
                geometry={nodes.safe_1_rect_8.geometry}
                material={materials["safe_1_rect_8 Material"]}
                castShadow
                receiveShadow
                position={[1.7, -0.98, 8.53]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                name="safe_1_rect_7"
                geometry={nodes.safe_1_rect_7.geometry}
                material={materials["safe_1_rect_7 Material"]}
                castShadow
                receiveShadow
                position={[1.7, 0.73, 8.53]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                name="safe_1_rect_6"
                geometry={nodes.safe_1_rect_6.geometry}
                material={materials["safe_1_rect_6 Material"]}
                castShadow
                receiveShadow
                position={[1.7, -2.57, 9.99]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                name="safe_1_rect_5"
                geometry={nodes.safe_1_rect_5.geometry}
                material={materials["safe_1_rect_5 Material"]}
                castShadow
                receiveShadow
                position={[1.7, -0.98, 9.99]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                name="safe_1_rect_4"
                geometry={nodes.safe_1_rect_4.geometry}
                material={materials["safe_1_rect_4 Material"]}
                castShadow
                receiveShadow
                position={[1.7, 0.73, 9.99]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                name="safe_1_rect_3"
                geometry={nodes.safe_1_rect_3.geometry}
                material={materials["safe_1_rect_3 Material"]}
                castShadow
                receiveShadow
                position={[1.7, -2.57, 11.58]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                name="safe_1_rect_2"
                geometry={nodes.safe_1_rect_2.geometry}
                material={materials["safe_1_rect_2 Material"]}
                castShadow
                receiveShadow
                position={[1.7, -0.98, 11.58]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                name="safe_1_rect_1"
                geometry={nodes.safe_1_rect_1.geometry}
                material={materials["safe_1_rect_1 Material"]}
                castShadow
                receiveShadow
                position={[1.7, 0.73, 11.58]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                name="safe_1_label"
                geometry={nodes.safe_1_label.geometry}
                material={materials["safe_1_label Material"]}
                castShadow
                receiveShadow
                position={[0.7, -0.92, 12.7]}
                rotation={[0, Math.PI / 2, 0]}
              />
            </group>
            <mesh
              name="safe-1_cube"
              geometry={nodes["safe-1_cube"].geometry}
              material={materials.safe_grey}
              castShadow
              receiveShadow
              position={[-4.5, 0, 0]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            />
          </group>
          <mesh
            name="carper_2"
            geometry={nodes.carper_2.geometry}
            material={materials.idk}
            castShadow
            receiveShadow
            position={[45.09, -154.38, -13.03]}
            rotation={[-Math.PI / 2, 0, 3.13]}
          />
          <group name="security_1" position={[94.79, 16.25, -175.18]}>
            <mesh
              name="security_1_rect_10"
              geometry={nodes.security_1_rect_10.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[7.55, -11.19, 0.82]}
            />
            <mesh
              name="security_1_rect_9"
              geometry={nodes.security_1_rect_9.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[7.55, -4.41, 0.82]}
            />
            <mesh
              name="security_1_rect_8"
              geometry={nodes.security_1_rect_8.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[7.55, 2.37, 0.82]}
            />
            <mesh
              name="security_1_rect_7"
              geometry={nodes.security_1_rect_7.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[0.57, -11.19, 0.82]}
            />
            <mesh
              name="security_1_rect_6"
              geometry={nodes.security_1_rect_6.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[0.57, -4.41, 0.82]}
            />
            <mesh
              name="security_1_rect_5"
              geometry={nodes.security_1_rect_5.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[0.57, 2.37, 0.82]}
            />
            <mesh
              name="security_1_rect_4"
              geometry={nodes.security_1_rect_4.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-6.6, -11.19, 0.82]}
            />
            <mesh
              name="security_1_rect_3"
              geometry={nodes.security_1_rect_3.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-6.6, -4.41, 0.82]}
            />
            <mesh
              name="security_1_rect_2"
              geometry={nodes.security_1_rect_2.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-6.6, 2.37, 0.82]}
            />
            <mesh
              name="security_1_rect_1"
              geometry={nodes.security_1_rect_1.geometry}
              material={materials.t_shirt_1}
              castShadow
              receiveShadow
              position={[0.24, 11.87, 0.86]}
            />
            <mesh
              name="security_1_cube"
              geometry={nodes.security_1_cube.geometry}
              material={materials.road}
              castShadow
              receiveShadow
              position={[0, 0, -0.89]}
            />
          </group>
          <mesh
            name="wall_shelf_1"
            geometry={nodes.wall_shelf_1.geometry}
            material={materials[" closet_1"]}
            castShadow
            receiveShadow
            position={[-155.82, 26.44, 113.11]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <group
            name="closet_1"
            position={[-111.22, -58.17, -29.86]}
            rotation={[0, Math.PI / 2, 0]}
          >
            <group name="t_shirt_12" position={[31.49, 45.42, -20.49]}>
              <mesh
                name="t_shirt_12_3"
                geometry={nodes.t_shirt_12_3.geometry}
                material={materials.t_shirt_4}
                castShadow
                receiveShadow
                position={[2.3, 0.94, -10.33]}
                rotation={[-Math.PI / 2, 0, 0.44]}
              />
              <mesh
                name="t_shirt_12_2"
                geometry={nodes.t_shirt_12_2.geometry}
                material={materials.t_shirt_4}
                castShadow
                receiveShadow
                position={[-2.75, 0.94, -10.32]}
                rotation={[-Math.PI / 2, 0, -0.44]}
              />
              <mesh
                name="t_shirt_12_1"
                geometry={nodes.t_shirt_12_1.geometry}
                material={materials.t_shirt_4}
                castShadow
                receiveShadow
                position={[0, -0.94, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="t_shirt_11" position={[1.7, 45.42, -20.49]}>
              <mesh
                name="t_shirt_11_3"
                geometry={nodes.t_shirt_11_3.geometry}
                material={materials.t_shirt_4}
                castShadow
                receiveShadow
                position={[2.3, 0.94, -10.33]}
                rotation={[-Math.PI / 2, 0, 0.44]}
              />
              <mesh
                name="t_shirt_11_2"
                geometry={nodes.t_shirt_11_2.geometry}
                material={materials.t_shirt_4}
                castShadow
                receiveShadow
                position={[-2.75, 0.94, -10.32]}
                rotation={[-Math.PI / 2, 0, -0.44]}
              />
              <mesh
                name="t_shirt_11_1"
                geometry={nodes.t_shirt_11_1.geometry}
                material={materials.t_shirt_4}
                castShadow
                receiveShadow
                position={[0, -0.94, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="t_shirt_10" position={[-27.94, 45.42, -20.49]}>
              <mesh
                name="t_shirt_10_3"
                geometry={nodes.t_shirt_10_3.geometry}
                material={materials.t_shirt_4}
                castShadow
                receiveShadow
                position={[2.3, 0.94, -10.33]}
                rotation={[-Math.PI / 2, 0, 0.44]}
              />
              <mesh
                name="t_shirt_10_2"
                geometry={nodes.t_shirt_10_2.geometry}
                material={materials.t_shirt_4}
                castShadow
                receiveShadow
                position={[-2.75, 0.94, -10.32]}
                rotation={[-Math.PI / 2, 0, -0.44]}
              />
              <mesh
                name="t_shirt_10_1"
                geometry={nodes.t_shirt_10_1.geometry}
                material={materials.t_shirt_4}
                castShadow
                receiveShadow
                position={[0, -0.94, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="t_shirt_9" position={[30.05, 2.04, -20.49]}>
              <mesh
                name="t_shirt_9_3"
                geometry={nodes.t_shirt_9_3.geometry}
                material={materials.t_shirt_3}
                castShadow
                receiveShadow
                position={[2.3, 0.94, -10.33]}
                rotation={[-Math.PI / 2, 0, 0.44]}
              />
              <mesh
                name="t_shirt_9_2"
                geometry={nodes.t_shirt_9_2.geometry}
                material={materials.t_shirt_3}
                castShadow
                receiveShadow
                position={[-2.75, 0.94, -10.32]}
                rotation={[-Math.PI / 2, 0, -0.44]}
              />
              <mesh
                name="t_shirt_9_1"
                geometry={nodes.t_shirt_9_1.geometry}
                material={materials.t_shirt_3}
                castShadow
                receiveShadow
                position={[0, -0.94, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="t_shirt_8" position={[0.91, 2.04, -20.49]}>
              <mesh
                name="t_shirt_8_3"
                geometry={nodes.t_shirt_8_3.geometry}
                material={materials.t_shirt_3}
                castShadow
                receiveShadow
                position={[2.3, 0.94, -10.33]}
                rotation={[-Math.PI / 2, 0, 0.44]}
              />
              <mesh
                name="t_shirt_8_2"
                geometry={nodes.t_shirt_8_2.geometry}
                material={materials.t_shirt_3}
                castShadow
                receiveShadow
                position={[-2.75, 0.94, -10.32]}
                rotation={[-Math.PI / 2, 0, -0.44]}
              />
              <mesh
                name="t_shirt_8_1"
                geometry={nodes.t_shirt_8_1.geometry}
                material={materials.t_shirt_3}
                castShadow
                receiveShadow
                position={[0, -0.94, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="t_shirt_7" position={[-28.11, 2.04, -20.49]}>
              <mesh
                name="t_shirt_7_3"
                geometry={nodes.t_shirt_7_3.geometry}
                material={materials.t_shirt_3}
                castShadow
                receiveShadow
                position={[2.3, 0.94, -10.33]}
                rotation={[-Math.PI / 2, 0, 0.44]}
              />
              <mesh
                name="t_shirt_7_2"
                geometry={nodes.t_shirt_7_2.geometry}
                material={materials.t_shirt_3}
                castShadow
                receiveShadow
                position={[-2.75, 0.94, -10.32]}
                rotation={[-Math.PI / 2, 0, -0.44]}
              />
              <mesh
                name="t_shirt_7_1"
                geometry={nodes.t_shirt_7_1.geometry}
                material={materials.t_shirt_3}
                castShadow
                receiveShadow
                position={[0, -0.94, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="t_shirt_6" position={[-28.11, -38.23, -20.49]}>
              <mesh
                name="t_shirt_6_3"
                geometry={nodes.t_shirt_6_3.geometry}
                material={materials["t_shirt_6_3 Material"]}
                castShadow
                receiveShadow
                position={[2.3, 0.94, -10.33]}
                rotation={[-Math.PI / 2, 0, 0.44]}
              />
              <mesh
                name="t_shirt_6_2"
                geometry={nodes.t_shirt_6_2.geometry}
                material={materials["t_shirt_6_2 Material"]}
                castShadow
                receiveShadow
                position={[-2.75, 0.94, -10.32]}
                rotation={[-Math.PI / 2, 0, -0.44]}
              />
              <mesh
                name="t_shirt_6_1"
                geometry={nodes.t_shirt_6_1.geometry}
                material={materials["t_shirt_6_1 Material"]}
                castShadow
                receiveShadow
                position={[0, -0.94, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="t_shirt_5" position={[29.86, -38.23, -20.49]}>
              <mesh
                name="t_shirt_5_3"
                geometry={nodes.t_shirt_5_3.geometry}
                material={materials.t_shirt_2}
                castShadow
                receiveShadow
                position={[2.3, 0.94, -10.33]}
                rotation={[-Math.PI / 2, 0, 0.44]}
              />
              <mesh
                name="t_shirt_5_2"
                geometry={nodes.t_shirt_5_2.geometry}
                material={materials.t_shirt_2}
                castShadow
                receiveShadow
                position={[-2.75, 0.94, -10.32]}
                rotation={[-Math.PI / 2, 0, -0.44]}
              />
              <mesh
                name="t_shirt_5_1"
                geometry={nodes.t_shirt_5_1.geometry}
                material={materials.t_shirt_2}
                castShadow
                receiveShadow
                position={[0, -0.94, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="t_shirt_4" position={[0.35, -38.23, -20.49]}>
              <mesh
                name="t_shirt_4_3"
                geometry={nodes.t_shirt_4_3.geometry}
                material={materials.t_shirt_2}
                castShadow
                receiveShadow
                position={[2.3, 0.94, -10.33]}
                rotation={[-Math.PI / 2, 0, 0.44]}
              />
              <mesh
                name="t_shirt_4_2"
                geometry={nodes.t_shirt_4_2.geometry}
                material={materials.t_shirt_2}
                castShadow
                receiveShadow
                position={[-2.75, 0.94, -10.32]}
                rotation={[-Math.PI / 2, 0, -0.44]}
              />
              <mesh
                name="t_shirt_4_1"
                geometry={nodes.t_shirt_4_1.geometry}
                material={materials.t_shirt_2}
                castShadow
                receiveShadow
                position={[0, -0.94, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="t_shirt_3" position={[29.72, -80.4, -20.49]}>
              <mesh
                name="t_shirt_3_3"
                geometry={nodes.t_shirt_3_3.geometry}
                material={materials.t_shirt_1}
                castShadow
                receiveShadow
                position={[2.3, 0.94, -10.33]}
                rotation={[-Math.PI / 2, 0, 0.44]}
              />
              <mesh
                name="t_shirt_3_2"
                geometry={nodes.t_shirt_3_2.geometry}
                material={materials.t_shirt_1}
                castShadow
                receiveShadow
                position={[-2.75, 0.94, -10.32]}
                rotation={[-Math.PI / 2, 0, -0.44]}
              />
              <mesh
                name="t_shirt_3_1"
                geometry={nodes.t_shirt_3_1.geometry}
                material={materials.t_shirt_1}
                castShadow
                receiveShadow
                position={[0, -0.94, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="t_shirt_2" position={[0.35, -80.4, -20.49]}>
              <mesh
                name="t_shirt_2_3"
                geometry={nodes.t_shirt_2_3.geometry}
                material={materials.t_shirt_1}
                castShadow
                receiveShadow
                position={[2.3, 0.94, -10.33]}
                rotation={[-Math.PI / 2, 0, 0.44]}
              />
              <mesh
                name="t_shirt_2_2"
                geometry={nodes.t_shirt_2_2.geometry}
                material={materials.t_shirt_1}
                castShadow
                receiveShadow
                position={[-2.75, 0.94, -10.32]}
                rotation={[-Math.PI / 2, 0, -0.44]}
              />
              <mesh
                name="t_shirt_2_1"
                geometry={nodes.t_shirt_2_1.geometry}
                material={materials.t_shirt_1}
                castShadow
                receiveShadow
                position={[0, -0.94, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="t_shirt_1" position={[-28.96, -80.4, -20.49]}>
              <mesh
                name="t_shirt_1_3"
                geometry={nodes.t_shirt_1_3.geometry}
                material={materials.t_shirt_1}
                castShadow
                receiveShadow
                position={[2.3, 0.94, -10.33]}
                rotation={[-Math.PI / 2, 0, 0.44]}
              />
              <mesh
                name="t_shirt_1_2"
                geometry={nodes.t_shirt_1_2.geometry}
                material={materials.t_shirt_1}
                castShadow
                receiveShadow
                position={[-2.75, 0.94, -10.32]}
                rotation={[-Math.PI / 2, 0, -0.44]}
              />
              <mesh
                name="t_shirt_1_1"
                geometry={nodes.t_shirt_1_1.geometry}
                material={materials.t_shirt_1}
                castShadow
                receiveShadow
                position={[0, -0.94, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <mesh
              name="closet_cube_8"
              geometry={nodes.closet_cube_8.geometry}
              material={materials[" closet_1"]}
              castShadow
              receiveShadow
              position={[2.64, 39.54, -30.21]}
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            />
            <mesh
              name="closet_cube_7"
              geometry={nodes.closet_cube_7.geometry}
              material={materials[" closet_1"]}
              castShadow
              receiveShadow
              position={[2.64, -3.65, -30.21]}
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            />
            <mesh
              name="closet_cube_6"
              geometry={nodes.closet_cube_6.geometry}
              material={materials[" closet_1"]}
              castShadow
              receiveShadow
              position={[2.64, -44.47, -30.21]}
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            />
            <mesh
              name="closet_cube_5"
              geometry={nodes.closet_cube_5.geometry}
              material={materials[" closet_1"]}
              castShadow
              receiveShadow
              position={[2.64, -86.47, -30.21]}
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            />
            <mesh
              name="closet_cube_4"
              geometry={nodes.closet_cube_4.geometry}
              material={materials[" closet_1"]}
              castShadow
              receiveShadow
              position={[2.64, 94.01, -30.31]}
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            />
            <mesh
              name="closet_cube_3"
              geometry={nodes.closet_cube_3.geometry}
              material={materials[" closet_1"]}
              castShadow
              receiveShadow
              position={[3.19, -0.01, -57.7]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            />
            <group name="closet_cube_10_g" position={[52.9, 3.88, 1.49]}>
              <mesh
                name="closet_cube_10"
                geometry={nodes.closet_cube_10.geometry}
                material={materials[" closet_1"]}
                castShadow
                receiveShadow
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              />
            </group>
            <group name="closet_cube_9_g" position={[-48.08, 3.76, 1.29]}>
              <mesh
                name="closet_cube_9"
                geometry={nodes.closet_cube_9.geometry}
                material={materials[" closet_1"]}
                castShadow
                receiveShadow
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              />
            </group>
            <mesh
              name="closet_cube_2"
              geometry={nodes.closet_cube_2.geometry}
              material={materials[" closet_1"]}
              castShadow
              receiveShadow
              position={[52.09, -0.01, -30.21]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="closet_cube_1"
              geometry={nodes.closet_cube_1.geometry}
              material={materials[" closet_1"]}
              castShadow
              receiveShadow
              position={[-46.68, -0.01, -30.21]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group
            name="robot"
            position={[-16.67, -127.38, 95.5]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <group
              name="robot_arm_left"
              position={[-0.2, -7.97, -0.4]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                name="robot_hand_rect_3_left"
                geometry={nodes.robot_hand_rect_3_left.geometry}
                material={materials.road}
                castShadow
                receiveShadow
                position={[1.52, -9.27, -0.83]}
              />
              <mesh
                name="robot_hand_rect_2_left"
                geometry={nodes.robot_hand_rect_2_left.geometry}
                material={materials.road}
                castShadow
                receiveShadow
                position={[-1.52, -9.27, -0.83]}
              />
              <mesh
                name="robot_hand_rect_1_left"
                geometry={nodes.robot_hand_rect_1_left.geometry}
                material={materials.road}
                castShadow
                receiveShadow
                position={[0.02, -7.44, -0.83]}
                rotation={[0, 0, Math.PI / 2]}
              />
              <mesh
                name="robot_arm_arm_left"
                geometry={nodes.robot_arm_arm_left.geometry}
                material={materials.road}
                castShadow
                receiveShadow
                position={[0.04, 1.2, -0.6]}
                rotation={[0, 0, Math.PI / 2]}
              />
              <mesh
                name="robot_arm_cube_left"
                geometry={nodes.robot_arm_cube_left.geometry}
                material={materials.road}
                castShadow
                receiveShadow
                position={[0.06, 10.27, 0.33]}
                rotation={[0, 0, Math.PI / 2]}
              />
            </group>
            <group
              name="robot_arm_right"
              position={[-0.2, 8.54, -0.4]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                name="robot_hand_rect_3_right"
                geometry={nodes.robot_hand_rect_3_right.geometry}
                material={materials.road}
                castShadow
                receiveShadow
                position={[1.52, -9.27, -0.16]}
              />
              <mesh
                name="robot_hand_rect_2_right"
                geometry={nodes.robot_hand_rect_2_right.geometry}
                material={materials.road}
                castShadow
                receiveShadow
                position={[-1.52, -9.27, -0.16]}
              />
              <mesh
                name="robot_hand_rect_1_right"
                geometry={nodes.robot_hand_rect_1_right.geometry}
                material={materials.road}
                castShadow
                receiveShadow
                position={[0.02, -7.44, -0.16]}
                rotation={[0, 0, Math.PI / 2]}
              />
              <mesh
                name="robot_arm_arm_right"
                geometry={nodes.robot_arm_arm_right.geometry}
                material={materials.road}
                castShadow
                receiveShadow
                position={[0.04, 1.2, 0.08]}
                rotation={[0, 0, Math.PI / 2]}
              />
              <mesh
                name="robot_arm_cube_right"
                geometry={nodes.robot_arm_cube_right.geometry}
                material={materials.road}
                castShadow
                receiveShadow
                position={[0.06, 10.27, -0.34]}
                rotation={[0, 0, Math.PI / 2]}
              />
            </group>
            <mesh
              name="robot_left_ear"
              geometry={nodes.robot_left_ear.geometry}
              material={materials.road}
              castShadow
              receiveShadow
              position={[22.8, -6.67, 0.08]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="robot_right_ear"
              geometry={nodes.robot_right_ear.geometry}
              material={materials.road}
              castShadow
              receiveShadow
              position={[22.8, 7.87, 0.08]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="robot_nose"
              geometry={nodes.robot_nose.geometry}
              material={materials.road}
              castShadow
              receiveShadow
              position={[23.07, 0.35, 6.58]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              name="robot_left_eye_ball"
              geometry={nodes.robot_left_eye_ball.geometry}
              material={materials.road}
              castShadow
              receiveShadow
              position={[25.01, -3.06, 6.86]}
            />
            <mesh
              name="robot_right_eye_ball"
              geometry={nodes.robot_right_eye_ball.geometry}
              material={materials.road}
              castShadow
              receiveShadow
              position={[25.01, 4.02, 6.86]}
            />
            <mesh
              name="robot_left_eye_black"
              geometry={nodes.robot_left_eye_black.geometry}
              material={materials.road}
              castShadow
              receiveShadow
              position={[25, -3.05, 7.67]}
            />
            <mesh
              name="robot_left_eye_white"
              geometry={nodes.robot_left_eye_white.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[25, -3.04, 7.67]}
            />
            <mesh
              name="robot_right_eye_white"
              geometry={nodes.robot_right_eye_white.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[25, 4, 7.67]}
            />
            <mesh
              name="robot_right_eye_black"
              geometry={nodes.robot_right_eye_black.geometry}
              material={materials.road}
              castShadow
              receiveShadow
              position={[25, 4, 7.67]}
            />
            <mesh
              name="robot_mouth_black"
              geometry={nodes.robot_mouth_black.geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[19.07, 0.5, 6.84]}
            />
            <mesh
              name="robot_mouth_white"
              geometry={nodes.robot_mouth_white.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[19.07, 0.5, 7.04]}
            />
            <mesh
              name="robot_cube_3"
              geometry={nodes.robot_cube_3.geometry}
              material={materials.arrow}
              castShadow
              receiveShadow
              position={[21.95, 0.59, -0.11]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="robot_cube_2"
              geometry={nodes.robot_cube_2.geometry}
              material={materials.arrow}
              castShadow
              receiveShadow
              position={[15.38, 0.5, -0.36]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            />
            <mesh
              name="robot_body"
              geometry={nodes.robot_body.geometry}
              material={materials.arrow}
              castShadow
              receiveShadow
              position={[-3.03, 0.27, -0.27]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="robot_botoom_cube"
              geometry={nodes.robot_botoom_cube.geometry}
              material={materials.arrow}
              castShadow
              receiveShadow
              position={[-21.31, -10.19, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="robot_leg_left"
              geometry={nodes.robot_leg_left.geometry}
              material={materials.road}
              castShadow
              receiveShadow
              position={[-21.37, -14.08, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="robot_leg_right"
              geometry={nodes.robot_leg_right.geometry}
              material={materials.road}
              castShadow
              receiveShadow
              position={[-21.45, 9.08, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="plant_2" position={[154.59, -105.03, 148.78]}>
            <mesh
              name="plant_2_4"
              geometry={nodes.plant_2_4.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[-5.54, -13.85, 10.56]}
              rotation={[-1.53, 0.07, 1.75]}
            />
            <mesh
              name="plant_2_3"
              geometry={nodes.plant_2_3.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[-2.01, -14.38, -3.72]}
              rotation={[-1.75, 0, -1.81]}
            />
            <mesh
              name="plant_2_2"
              geometry={nodes.plant_2_2.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[7.08, -12.64, 5.57]}
              rotation={[-Math.PI / 2, 0.1, -Math.PI]}
            />
            <mesh
              name="plant_2_1"
              geometry={nodes.plant_2_1.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[-7.68, -11.83, 5.57]}
              rotation={[-Math.PI / 2, -0.06, 0]}
            />
            <mesh
              name="pot_2"
              geometry={nodes.pot_2.geometry}
              material={materials.pot}
              castShadow
              receiveShadow
              position={[-2.55, -217.56, 3.63]}
            />
          </group>
          <group
            name="room_2_windows_frame"
            position={[-51.57, 37.51, -175.53]}
            rotation={[0, -Math.PI / 2, 0]}
          >
            <mesh
              name="room_2_windows_frame_rect_5"
              geometry={nodes.room_2_windows_frame_rect_5.geometry}
              material={materials.sofa_2}
              castShadow
              receiveShadow
              position={[-1.5, 2.62, -53.29]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            />
            <mesh
              name="room_2_windows_frame_rect_4"
              geometry={nodes.room_2_windows_frame_rect_4.geometry}
              material={materials.sofa_2}
              castShadow
              receiveShadow
              position={[-1.5, 2.33, 53.29]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            />
            <mesh
              name="room_2_windows_frame_rect_3"
              geometry={nodes.room_2_windows_frame_rect_3.geometry}
              material={materials.sofa_2}
              castShadow
              receiveShadow
              position={[-1.5, -23.6, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="room_2_windows_frame_rect_2"
              geometry={nodes.room_2_windows_frame_rect_2.geometry}
              material={materials.sofa_2}
              castShadow
              receiveShadow
              position={[-1.5, -69.05, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="room_2_windows_frame_rect_1"
              geometry={nodes.room_2_windows_frame_rect_1.geometry}
              material={materials.sofa_2}
              castShadow
              receiveShadow
              position={[-1.5, 69.05, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
          </group>
          <mesh
            name="room_2_window"
            geometry={nodes.room_2_window.geometry}
            material={materials.room2_floor}
            castShadow
            receiveShadow
            position={[-52.31, 37.48, -182.64]}
          >
            <mesh
              name="room_2_window_cube"
              geometry={nodes.room_2_window_cube.geometry}
              material={materials["room_2_window_cube Material"]}
              visible={false}
              castShadow
              receiveShadow
            />
            <mesh
              name="room_2_wall_right"
              geometry={nodes.room_2_wall_right.geometry}
              material={materials.room2_floor}
              visible={false}
              castShadow
              receiveShadow
              position={[52.31, -34.98, -17.36]}
            />
          </mesh>
          <mesh
            name="room_2_wall_left"
            geometry={nodes.room_2_wall_left.geometry}
            material={materials.room2_floor}
            castShadow
            receiveShadow
            position={[-200, 2.5, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="room_2_floor"
            geometry={nodes.room_2_floor.geometry}
            material={materials.room2_floor}
            castShadow
            receiveShadow
            position={[0, -177.5, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <group name="Room1" position={[100, 1064.55, 100]}>
          <mesh
            name="ball_1"
            geometry={nodes.ball_1.geometry}
            material={materials.arrow}
            castShadow
            receiveShadow
            position={[5.94, -84.5, 17]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <group name="resume" position={[-75, 39.27, -175]}>
            <mesh
              name="resume_rect_2"
              geometry={nodes.resume_rect_2.geometry}
              material={materials["resume_rect_2 Material"]}
              castShadow
              receiveShadow
              position={[0, -0.27, 1]}
            />
            <mesh
              name="resume_rect_1"
              geometry={nodes.resume_rect_1.geometry}
              material={materials.pot}
              castShadow
              receiveShadow
              position={[0, 0, -2]}
            />
          </group>
          <group name="carpet_1" position={[87.82, -154.45, 34]}>
            <mesh
              name="carpet_1_circle_2"
              geometry={nodes.carpet_1_circle_2.geometry}
              material={materials.room1_floor}
              castShadow
              receiveShadow
              position={[0, 0.44, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="carpet_1_circle_1"
              geometry={nodes.carpet_1_circle_1.geometry}
              material={materials.idk}
              castShadow
              receiveShadow
              position={[0, -1.44, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="plant_1" position={[-122.37, -105.03, -143.73]}>
            <mesh
              name="plant_1_4"
              geometry={nodes.plant_1_4.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[-5.54, -13.85, 10.56]}
              rotation={[-1.53, 0.07, 1.75]}
            />
            <mesh
              name="plant_1_3"
              geometry={nodes.plant_1_3.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[-2.01, -14.38, -3.72]}
              rotation={[-1.75, 0, -1.81]}
            />
            <mesh
              name="plant_1_2"
              geometry={nodes.plant_1_2.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[7.08, -12.64, 5.57]}
              rotation={[-Math.PI / 2, 0.1, -Math.PI]}
            />
            <mesh
              name="plant_1_1"
              geometry={nodes.plant_1_1.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[-7.68, -11.83, 5.57]}
              rotation={[-Math.PI / 2, -0.06, 0]}
            />
            <mesh
              name="pot_1"
              geometry={nodes.pot_1.geometry}
              material={materials.pot}
              castShadow
              receiveShadow
              position={[-2.55, -217.56, 3.63]}
            />
          </group>
          <group
            name="cv_1"
            position={[131, -89.95, 22.83]}
            rotation={[0, Math.PI / 4, 0]}
          >
            <mesh
              name="cv_rect_3"
              geometry={nodes.cv_rect_3.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[2.73, 4.61, 3.4]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="cv_rect_2"
              geometry={nodes.cv_rect_2.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-2.78, -3.02, 4.17]}
              rotation={[-Math.PI / 2, 0, -0.39]}
            />
            <mesh
              name="cv_rect_1"
              geometry={nodes.cv_rect_1.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-7.2, -0.06, -5.13]}
              rotation={[-Math.PI / 2, 0, -0.68]}
            />
          </group>
          <group
            name="controller_1"
            position={[55.57, -91.03, 7.95]}
            rotation={[0.09, 0, 0]}
            scale={1.66}
          >
            <mesh
              name="controllet_1_circle_1"
              geometry={nodes.controllet_1_circle_1.geometry}
              material={materials["controllet_1_circle_1 Material"]}
              castShadow
              receiveShadow
              position={[-1.79, 2.01, -0.79]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1.72}
            />
            <mesh
              name="controllet_1_circle_11"
              geometry={nodes.controllet_1_circle_11.geometry}
              material={materials["controllet_1_circle_11 Material"]}
              castShadow
              receiveShadow
              position={[1.81, 2.01, -0.79]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1.72}
            />
            <mesh
              name="controllet_1_cube_3"
              geometry={nodes.controllet_1_cube_3.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[6.11, 0.27, 0.82]}
              rotation={[-Math.PI / 2, 0, 2.18]}
              scale={0.62}
            />
            <mesh
              name="controllet_1_cube_2"
              geometry={nodes.controllet_1_cube_2.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-6.11, 0.27, 0.59]}
              rotation={[-Math.PI / 2, 0, 0.96]}
              scale={0.62}
            />
            <mesh
              name="controllet_1_cube_1"
              geometry={nodes.controllet_1_cube_1.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-0.07, -0.01, -1.45]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="tv" position={[83.06, -63.48, 177.1]}>
            <mesh
              name="tv_tri_2"
              geometry={nodes.tv_tri_2.geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[-11.8, -37.9, 0]}
              rotation={[Math.PI / 2, 1.22, -Math.PI / 2]}
            />
            <mesh
              name="tv_tri_1"
              geometry={nodes.tv_tri_1.geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[9.25, -37.9, 0]}
              rotation={[-Math.PI / 2, 1.22, Math.PI / 2]}
            />
            <mesh
              name="tv_rect_1"
              geometry={nodes.tv_rect_1.geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[0, 6.06, -1.42]}
            />
          </group>
          <group name="tv_table" position={[83, -131.7, 177.5]}>
            <mesh
              name="tv_table_cyl_4"
              geometry={nodes.tv_table_cyl_4.geometry}
              material={materials["tv_table_cyl_4 Material"]}
              castShadow
              receiveShadow
              position={[65.86, -13.89, 9.39]}
              rotation={[0, 0, 0.26]}
            />
            <mesh
              name="tv_table_cyl_3"
              geometry={nodes.tv_table_cyl_3.geometry}
              material={materials["tv_table_cyl_3 Material"]}
              castShadow
              receiveShadow
              position={[-65.57, -13.82, 9.39]}
              rotation={[0, 0, -0.26]}
            />
            <mesh
              name="tv_table_cyl_2"
              geometry={nodes.tv_table_cyl_2.geometry}
              material={materials["tv_table_cyl_2 Material"]}
              castShadow
              receiveShadow
              position={[66.08, -13.83, -9.5]}
              rotation={[0, 0, 0.26]}
            />
            <mesh
              name="tv_table_cyl_1"
              geometry={nodes.tv_table_cyl_1.geometry}
              material={materials["tv_table_cyl_1 Material"]}
              castShadow
              receiveShadow
              position={[-65.32, -13.89, -9.5]}
              rotation={[0, 0, -0.26]}
            />
            <mesh
              name="tv_table_rect"
              geometry={nodes.tv_table_rect.geometry}
              material={materials.piano_chair_leg}
              castShadow
              receiveShadow
              position={[0, -4.44, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="tabel_1" position={[76.5, -124.59, 13.3]}>
            <mesh
              name="table_1_leg_4"
              geometry={nodes.table_1_leg_4.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-84.73, -5.23, 33.5]}
            />
            <mesh
              name="table_1_leg_3"
              geometry={nodes.table_1_leg_3.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[87.44, -5.23, 33.5]}
            />
            <mesh
              name="table_1_leg_2"
              geometry={nodes.table_1_leg_2.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[87.44, -5.23, -32.5]}
            />
            <mesh
              name="table_1_leg_1"
              geometry={nodes.table_1_leg_1.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-85, -5.23, -32.5]}
            />
            <mesh
              name="table_1_top"
              geometry={nodes.table_1_top.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[0, 18.38, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="piano_chair" position={[-110.07, -137.3, 84.52]}>
            <mesh
              name="piano_chair_cube"
              geometry={nodes.piano_chair_cube.geometry}
              material={materials["piano_chair_cube Material"]}
              castShadow
              receiveShadow
              position={[0, 14.32, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="piano_chair_cyl"
              geometry={nodes.piano_chair_cyl.geometry}
              material={materials.piano_chair_leg}
              castShadow
              receiveShadow
              position={[-11.85, -3.32, -11.89]}
            />
          </group>
          <group name="piano" position={[-144.75, -94.21, 153.21]}>
            <mesh
              name="black_keys"
              geometry={nodes.black_keys.geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[1.35, 18.46, -12.82]}
            />
            <mesh
              name="white_keys"
              geometry={nodes.white_keys.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[3.94, 16.97, -4.22]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1, 1.07, 1]}
            />
            <mesh
              name="under_key"
              geometry={nodes.under_key.geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[5.95, 14.45, -69.77]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="top_body"
              geometry={nodes.top_body.geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[-14.66, 46.46, -68.24]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="back"
              geometry={nodes.back.geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[-20.82, -0.26, -68.98]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <group name="right leg" position={[0, 0, -139.15]}>
              <mesh
                name="right_leg_cube_4"
                geometry={nodes.right_leg_cube_4.geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[-12.24, 0, 0.73]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="right_leg_cube_3"
                geometry={nodes.right_leg_cube_3.geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[8.75, -53.87, 0.73]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="right_leg_cube_2"
                geometry={nodes.right_leg_cube_2.geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[12.16, 14.95, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="right_leg_cube_1"
                geometry={nodes.right_leg_cube_1.geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[19.82, -26.22, 0.97]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="left lef">
              <mesh
                name="left_leg_cube_4"
                geometry={nodes.left_leg_cube_4.geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[-12.24, 0, 0.73]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="left_leg_cube_3"
                geometry={nodes.left_leg_cube_3.geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[8.75, -53.87, 0.73]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="left_leg_cube_2"
                geometry={nodes.left_leg_cube_2.geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[12.16, 14.95, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="left_leg_cube_1"
                geometry={nodes.left_leg_cube_1.geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[19.82, -26.22, 0.97]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
          </group>
          <group name="sofa" position={[107.72, -94.77, -126.56]}>
            <mesh
              name="sofa_cube_3"
              geometry={nodes.sofa_cube_3.geometry}
              material={materials.sofa_2}
              castShadow
              receiveShadow
              position={[0.5, 20.33, -36.5]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="sofa_cube_2"
              geometry={nodes.sofa_cube_2.geometry}
              material={materials.sofa_2}
              castShadow
              receiveShadow
              position={[0, -20.27, 0]}
            />
            <mesh
              name="sofa_cube_1"
              geometry={nodes.sofa_cube_1.geometry}
              material={materials.sofa_2}
              castShadow
              receiveShadow
              position={[0, -46.51, 0]}
            />
          </group>
          <group name="linkedin" position={[101.41, 42.28, -124]} scale={0.1}>
            <mesh
              name="Merged Geometry"
              geometry={nodes["Merged Geometry"].geometry}
              material={materials["Merged Geometry Material"]}
              receiveShadow
              position={[-10.75, 3.5, -511]}
            />
            <mesh
              name="linkedin_rect"
              geometry={nodes.linkedin_rect.geometry}
              material={materials["linkedin_rect Material"]}
              castShadow
              receiveShadow
              position={[-10.69, 0, -532.64]}
            />
          </group>
          <mesh
            name="room_1_wall_right"
            geometry={nodes.room_1_wall_right.geometry}
            material={materials.room1_floor}
            castShadow
            receiveShadow
            position={[0, 2.5, -200]}
          />
          <group name="room_1_windows_frame" position={[-175.5, 55.45, -41.52]}>
            <mesh
              name="room_1_windows_frame_rect_5"
              geometry={nodes.room_1_windows_frame_rect_5.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-1.5, 2.62, -53.29]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            />
            <mesh
              name="room_1_windows_frame_rect_4"
              geometry={nodes.room_1_windows_frame_rect_4.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-1.5, 2.33, 53.29]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            />
            <mesh
              name="room_1_windows_frame_rect_3"
              geometry={nodes.room_1_windows_frame_rect_3.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-1.5, -23.6, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="room_1_windows_frame_rect_2"
              geometry={nodes.room_1_windows_frame_rect_2.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-1.5, -69.05, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="room_1_windows_frame_rect_1"
              geometry={nodes.room_1_windows_frame_rect_1.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-1.5, 69.05, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
          </group>
          <mesh
            name="room_1_window"
            geometry={nodes.room_1_window.geometry}
            material={materials.room1_floor}
            castShadow
            receiveShadow
            position={[-189, 2.5, 0]}
          >
            <mesh
              name="room_1_window_cube"
              geometry={nodes.room_1_window_cube.geometry}
              material={materials["room_1_window_cube Material"]}
              visible={false}
              castShadow
              receiveShadow
              position={[0.08, 52.33, -41.52]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="room_1_wall_left"
              geometry={nodes.room_1_wall_left.geometry}
              material={materials.room1_floor}
              visible={false}
              castShadow
              receiveShadow
              position={[-11, 0, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
          </mesh>
          <mesh
            name="room_1_floor"
            geometry={nodes.room_1_floor.geometry}
            material={materials.room1_floor}
            castShadow
            receiveShadow
            position={[0, -177.5, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <pointLight
          name="Point Light"
          castShadow
          intensity={1.9}
          distance={2000}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={100}
          shadow-camera-far={100000}
          position={[945.96, 1023.41, 666.99]}
        />
        <mesh
          name="ground"
          geometry={nodes.ground.geometry}
          material={materials["ground Material"]}
          castShadow
          receiveShadow
          position={[4, 1, -4]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <OrthographicCamera
          name="Camera"
          makeDefault={true}
          zoom={0.6}
          far={100000}
          near={-100000}
          up={[0, 1, 0]}
          position={[-334.47, 1396.39, 1155.59]}
          rotation={[-Math.PI / 4, 0.62, Math.PI / 6]}
        />
        <hemisphereLight
          name="Default Ambient Light"
          intensity={0.75}
          color="#eaeaea"
          position={[0, 1, 0]}
        />
      </group>
    </>
  );
}
