/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/gprjBHugYEihqeMu/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#464646"]} />
      <group {...props} dispose={null}>
        <group name="Road" position={[-1370.65, 178.93, -0.93]}>
          <group
            name="arrow 4"
            position={[-1017.64, -139.93, 96]}
            rotation={[-Math.PI, 0, -Math.PI]}
          >
            <mesh
              name="arrow_tri"
              geometry={nodes.arrow_tri.geometry}
              material={materials.arrow}
              castShadow
              receiveShadow
              position={[-50.16, -4, 0]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            />
            <mesh
              name="arrow_rect"
              geometry={nodes.arrow_rect.geometry}
              material={materials.arrow}
              castShadow
              receiveShadow
              position={[25.66, -4, 1.43]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group
            name="arrow 3"
            position={[-221.78, -139.93, 96]}
            rotation={[-Math.PI, 0, -Math.PI]}
          >
            <mesh
              name="arrow_tri1"
              geometry={nodes.arrow_tri1.geometry}
              material={materials.arrow}
              castShadow
              receiveShadow
              position={[-50.16, -4, 0]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            />
            <mesh
              name="arrow_rect1"
              geometry={nodes.arrow_rect1.geometry}
              material={materials.arrow}
              castShadow
              receiveShadow
              position={[25.66, -4, 1.43]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="arrow 2" position={[-401.58, -139.93, 96]}>
            <mesh
              name="arrow_tri2"
              geometry={nodes.arrow_tri2.geometry}
              material={materials.arrow}
              castShadow
              receiveShadow
              position={[-50.16, -4, 0]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            />
            <mesh
              name="arrow_rect2"
              geometry={nodes.arrow_rect2.geometry}
              material={materials.arrow}
              castShadow
              receiveShadow
              position={[25.66, -4, 1.43]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="arrow" position={[691.53, -139.93, 96]}>
            <mesh
              name="arrow_tri3"
              geometry={nodes.arrow_tri3.geometry}
              material={materials.arrow}
              castShadow
              receiveShadow
              position={[-50.16, -4, 0]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            />
            <mesh
              name="arrow_rect3"
              geometry={nodes.arrow_rect3.geometry}
              material={materials.arrow}
              castShadow
              receiveShadow
              position={[25.66, -4, 1.43]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="dead_end" position={[-1315.16, -61.82, 15.33]}>
            <group
              name="Text"
              position={[4.15, 62.22, 2.34]}
              rotation={[Math.PI, 1.55, Math.PI]}
            >
              <mesh
                name="D"
                geometry={nodes.D.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-28.33, 0, 0]}
              />
              <mesh
                name="E"
                geometry={nodes.E.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-13.69, 0, 0]}
              />
              <mesh
                name="A"
                geometry={nodes.A.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-0.7, 0, 0]}
              />
              <mesh
                name="D1"
                geometry={nodes.D1.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[13.69, 0, 0]}
              />
              <mesh
                name="E1"
                geometry={nodes.E1.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-21.74, -24, 0]}
              />
              <mesh
                name="N"
                geometry={nodes.N.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[-8.75, -24, 0]}
              />
              <mesh
                name="D2"
                geometry={nodes.D2.geometry}
                material={materials["My Text Material"]}
                castShadow
                receiveShadow
                position={[7.1, -24, 0]}
              />
            </group>
            <mesh
              name="Rectangle"
              geometry={nodes.Rectangle.geometry}
              material={materials["Rectangle Material"]}
              castShadow
              receiveShadow
              position={[-0.4, 59.68, 0.04]}
              rotation={[-Math.PI, 1.55, 2.36]}
              scale={1.59}
            />
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials["Cylinder Material"]}
              castShadow
              receiveShadow
              position={[-3.02, -32.27, 0.3]}
            />
          </group>
          <group name="sign 5" position={[-1233.4, -177.35, -268.69]}>
            <mesh
              name="Rectangle1"
              geometry={nodes.Rectangle1.geometry}
              material={materials["Rectangle1 Material"]}
              castShadow
              receiveShadow
              position={[-0.03, 55.22, 5.16]}
            />
            <mesh
              name="Cube 2"
              geometry={nodes["Cube 2"].geometry}
              material={materials.pot}
              castShadow
              receiveShadow
              position={[0, 54.97, 2.65]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[0.38, -32.67, -2.66]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="sign 4" position={[-471.01, -177.35, -268.69]}>
            <mesh
              name="Rectangle2"
              geometry={nodes.Rectangle2.geometry}
              material={materials["Rectangle2 Material"]}
              castShadow
              receiveShadow
              position={[-0.03, 55.22, 5.16]}
            />
            <mesh
              name="Cube 21"
              geometry={nodes["Cube 21"].geometry}
              material={materials.pot}
              castShadow
              receiveShadow
              position={[0, 54.97, 2.65]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube1"
              geometry={nodes.Cube1.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[0.38, -32.67, -2.66]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="sign 3" position={[191.62, -177.35, -268.69]}>
            <mesh
              name="Rectangle3"
              geometry={nodes.Rectangle3.geometry}
              material={materials["Rectangle3 Material"]}
              castShadow
              receiveShadow
              position={[-0.03, 55.22, 5.16]}
            />
            <mesh
              name="Cube 22"
              geometry={nodes["Cube 22"].geometry}
              material={materials.pot}
              castShadow
              receiveShadow
              position={[0, 54.97, 2.65]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube2"
              geometry={nodes.Cube2.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[0.38, -32.67, -2.66]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="sign 7" position={[32.81, -177.35, -268.69]}>
            <mesh
              name="Rectangle4"
              geometry={nodes.Rectangle4.geometry}
              material={materials["Rectangle4 Material"]}
              castShadow
              receiveShadow
              position={[-0.03, 55.22, 5.16]}
            />
            <mesh
              name="Cube 23"
              geometry={nodes["Cube 23"].geometry}
              material={materials.pot}
              castShadow
              receiveShadow
              position={[0, 54.97, 2.65]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube3"
              geometry={nodes.Cube3.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[0.38, -32.67, -2.66]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="sign 6" position={[-1081.85, -177.35, -268.69]}>
            <mesh
              name="Rectangle5"
              geometry={nodes.Rectangle5.geometry}
              material={materials["Rectangle5 Material"]}
              castShadow
              receiveShadow
              position={[-0.03, 55.22, 5.16]}
            />
            <mesh
              name="Cube 24"
              geometry={nodes["Cube 24"].geometry}
              material={materials.pot}
              castShadow
              receiveShadow
              position={[0, 54.97, 2.65]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube4"
              geometry={nodes.Cube4.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[0.38, -32.67, -2.66]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="sign 2" position={[350.31, -177.35, -268.69]}>
            <mesh
              name="Rectangle6"
              geometry={nodes.Rectangle6.geometry}
              material={materials["Rectangle6 Material"]}
              castShadow
              receiveShadow
              position={[-0.03, 55.22, 5.16]}
            />
            <mesh
              name="Cube 25"
              geometry={nodes["Cube 25"].geometry}
              material={materials.pot}
              castShadow
              receiveShadow
              position={[0, 54.97, 2.65]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube5"
              geometry={nodes.Cube5.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[0.38, -32.67, -2.66]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="sign" position={[-622.1, -177.35, -268.69]}>
            <mesh
              name="Rectangle7"
              geometry={nodes.Rectangle7.geometry}
              material={materials["Rectangle7 Material"]}
              castShadow
              receiveShadow
              position={[-0.03, 55.22, 5.16]}
            />
            <mesh
              name="Cube 26"
              geometry={nodes["Cube 26"].geometry}
              material={materials.pot}
              castShadow
              receiveShadow
              position={[0, 54.97, 2.65]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube6"
              geometry={nodes.Cube6.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[0.38, -32.67, -2.66]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group
            name="node"
            position={[-1046.55, -176.93, 312.43]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              name="N1"
              geometry={nodes.N1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-314.45, 13.5, 0]}
            />
            <mesh
              name="o"
              geometry={nodes.o.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-256.97, 13.5, 0]}
            />
            <mesh
              name="d"
              geometry={nodes.d.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-211.21, 13.5, 0]}
            />
            <mesh
              name="e"
              geometry={nodes.e.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-165.45, 13.5, 0]}
            />
            <mesh
              name="/"
              geometry={nodes["/"].geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-102.86, 13.5, 0]}
            />
            <mesh
              name="E2"
              geometry={nodes.E2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-49.45, 13.5, 0]}
            />
            <mesh
              name="x"
              geometry={nodes.x.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-2.35, 13.5, 0]}
            />
            <mesh
              name="p"
              geometry={nodes.p.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[38.19, 13.5, 0]}
            />
            <mesh
              name="r"
              geometry={nodes.r.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[83.95, 13.5, 0]}
            />
            <mesh
              name="e1"
              geometry={nodes.e1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[111.56, 13.5, 0]}
            />
            <mesh
              name="s"
              geometry={nodes.s.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[154.13, 13.5, 0]}
            />
            <mesh
              name="s1"
              geometry={nodes.s1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[196.24, 13.5, 0]}
            />
            <mesh
              name="M"
              geometry={nodes.M.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-314.45, -73.5, 0]}
            />
            <mesh
              name="o1"
              geometry={nodes.o1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-243.69, -73.5, 0]}
            />
            <mesh
              name="n"
              geometry={nodes.n.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-197.93, -73.5, 0]}
            />
            <mesh
              name="g"
              geometry={nodes.g.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-152.16, -73.5, 0]}
            />
            <mesh
              name="o2"
              geometry={nodes.o2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-106.4, -73.5, 0]}
            />
            <mesh
              name="D3"
              geometry={nodes.D3.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-60.64, -73.5, 0]}
            />
            <mesh
              name="B"
              geometry={nodes.B.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-7.57, -73.5, 0]}
            />
          </group>
          <group
            name="react"
            position={[-298.27, -176.93, 312.43]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              name="R"
              geometry={nodes.R.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-234, 13.5, 0]}
            />
            <mesh
              name="e2"
              geometry={nodes.e2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-180.64, 13.5, 0]}
            />
            <mesh
              name="a"
              geometry={nodes.a.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-138.07, 13.5, 0]}
            />
            <mesh
              name="c"
              geometry={nodes.c.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-93.76, 13.5, 0]}
            />
            <mesh
              name="t"
              geometry={nodes.t.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-51.01, 13.5, 0]}
            />
            <mesh
              name="/1"
              geometry={nodes["/1"].geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-3.16, 13.5, 0]}
            />
            <mesh
              name="N2"
              geometry={nodes.N2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[50.26, 13.5, 0]}
            />
            <mesh
              name="e3"
              geometry={nodes.e3.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[107.74, 13.5, 0]}
            />
            <mesh
              name="x1"
              geometry={nodes.x1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[150.31, 13.5, 0]}
            />
            <mesh
              name="t1"
              geometry={nodes.t1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[190.85, 13.5, 0]}
            />
            <mesh
              name="R1"
              geometry={nodes.R1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-234, -73.5, 0]}
            />
            <mesh
              name="e4"
              geometry={nodes.e4.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-180.64, -73.5, 0]}
            />
            <mesh
              name="a1"
              geometry={nodes.a1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-138.07, -73.5, 0]}
            />
            <mesh
              name="c1"
              geometry={nodes.c1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-93.76, -73.5, 0]}
            />
            <mesh
              name="t2"
              geometry={nodes.t2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-51.01, -73.5, 0]}
            />
            <mesh
              name="N3"
              geometry={nodes.N3.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-3.16, -73.5, 0]}
            />
            <mesh
              name="a2"
              geometry={nodes.a2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[54.32, -73.5, 0]}
            />
            <mesh
              name="t3"
              geometry={nodes.t3.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[98.63, -73.5, 0]}
            />
            <mesh
              name="i"
              geometry={nodes.i.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[126.47, -73.5, 0]}
            />
            <mesh
              name="i1"
              geometry={nodes.i1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[126.47, -73.5, 0]}
            />
            <mesh
              name="v"
              geometry={nodes.v.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[146.77, -73.5, 0]}
            />
            <mesh
              name="e5"
              geometry={nodes.e5.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[187.31, -73.5, 0]}
            />
          </group>
          <group
            name="html"
            position={[559.21, -176.93, 312.43]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              name="H"
              geometry={nodes.H.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-323.58, 13.5, 0]}
            />
            <mesh
              name="T"
              geometry={nodes.T.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-266.1, 13.5, 0]}
            />
            <mesh
              name="M1"
              geometry={nodes.M1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-218.89, 13.5, 0]}
            />
            <mesh
              name="L"
              geometry={nodes.L.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-148.13, 13.5, 0]}
            />
            <mesh
              name="/2"
              geometry={nodes["/2"].geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-84.62, 13.5, 0]}
            />
            <mesh
              name="C"
              geometry={nodes.C.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-31.2, 13.5, 0]}
            />
            <mesh
              name="S"
              geometry={nodes.S.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[19.84, 13.5, 0]}
            />
            <mesh
              name="S1"
              geometry={nodes.S1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[70.07, 13.5, 0]}
            />
            <mesh
              name="/3"
              geometry={nodes["/3"].geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[140.31, 13.5, 0]}
            />
            <mesh
              name="J"
              geometry={nodes.J.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[193.73, 13.5, 0]}
            />
            <mesh
              name="S2"
              geometry={nodes.S2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[238.15, 13.5, 0]}
            />
          </group>
          <group name="tree 6" position={[-1470.23, 9.2, -276.72]}>
            <group name="tree_top" position={[0, 56.46, 0]}>
              <mesh
                name="Cone 3"
                geometry={nodes["Cone 3"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, 58.55, 0]}
              />
              <mesh
                name="Cone 2"
                geometry={nodes["Cone 2"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, 1.77, 0]}
              />
              <mesh
                name="Cone"
                geometry={nodes.Cone.geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, -58.55, 0]}
              />
            </group>
            <mesh
              name="tree_body"
              geometry={nodes.tree_body.geometry}
              material={materials.piano_chair_leg}
              castShadow
              receiveShadow
              position={[1.21, -70.51, 4]}
            />
          </group>
          <group name="tree 5" position={[-845.45, 9.2, -276.72]}>
            <group name="tree_top1" position={[0, 56.46, 0]}>
              <mesh
                name="Cone 31"
                geometry={nodes["Cone 31"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, 58.55, 0]}
              />
              <mesh
                name="Cone 21"
                geometry={nodes["Cone 21"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, 1.77, 0]}
              />
              <mesh
                name="Cone1"
                geometry={nodes.Cone1.geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, -58.55, 0]}
              />
            </group>
            <mesh
              name="tree_body1"
              geometry={nodes.tree_body1.geometry}
              material={materials.piano_chair_leg}
              castShadow
              receiveShadow
              position={[1.21, -70.51, 4]}
            />
          </group>
          <group name="tree 3" position={[-215.2, 9.2, -276.72]}>
            <group name="tree_top2" position={[0, 56.46, 0]}>
              <mesh
                name="Cone 32"
                geometry={nodes["Cone 32"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, 58.55, 0]}
              />
              <mesh
                name="Cone 22"
                geometry={nodes["Cone 22"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, 1.77, 0]}
              />
              <mesh
                name="Cone2"
                geometry={nodes.Cone2.geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, -58.55, 0]}
              />
            </group>
            <mesh
              name="tree_body2"
              geometry={nodes.tree_body2.geometry}
              material={materials.piano_chair_leg}
              castShadow
              receiveShadow
              position={[1.21, -70.51, 4]}
            />
          </group>
          <group name="tree 2" position={[616.95, 9.2, -287.47]}>
            <group name="tree_top3" position={[0, 56.46, 0]}>
              <mesh
                name="Cone 33"
                geometry={nodes["Cone 33"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, 58.55, 0]}
              />
              <mesh
                name="Cone 23"
                geometry={nodes["Cone 23"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, 1.77, 0]}
              />
              <mesh
                name="Cone3"
                geometry={nodes.Cone3.geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, -58.55, 0]}
              />
            </group>
            <mesh
              name="tree_body3"
              geometry={nodes.tree_body3.geometry}
              material={materials.piano_chair_leg}
              castShadow
              receiveShadow
              position={[1.21, -70.51, 4]}
            />
          </group>
          <group name="tree 4" position={[-647.88, 9.2, 273.54]}>
            <group name="tree_top4" position={[0, 56.46, 0]}>
              <mesh
                name="Cone 34"
                geometry={nodes["Cone 34"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, 58.55, 0]}
              />
              <mesh
                name="Cone 24"
                geometry={nodes["Cone 24"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, 1.77, 0]}
              />
              <mesh
                name="Cone4"
                geometry={nodes.Cone4.geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, -58.55, 0]}
              />
            </group>
            <mesh
              name="tree_body4"
              geometry={nodes.tree_body4.geometry}
              material={materials.piano_chair_leg}
              castShadow
              receiveShadow
              position={[1.21, -70.51, 4]}
            />
          </group>
          <group name="tree" position={[165.19, 9.2, 273.54]}>
            <group name="tree_top5" position={[0, 56.46, 0]}>
              <mesh
                name="Cone 35"
                geometry={nodes["Cone 35"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, 58.55, 0]}
              />
              <mesh
                name="Cone 25"
                geometry={nodes["Cone 25"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, 1.77, 0]}
              />
              <mesh
                name="Cone5"
                geometry={nodes.Cone5.geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[0, -58.55, 0]}
              />
            </group>
            <mesh
              name="tree_body5"
              geometry={nodes.tree_body5.geometry}
              material={materials.piano_chair_leg}
              castShadow
              receiveShadow
              position={[1.21, -70.51, 4]}
            />
          </group>
          <mesh
            name="Road_white"
            geometry={nodes.Road_white.geometry}
            material={materials.room1_floor}
            castShadow
            receiveShadow
            position={[738.99, -142.42, 0.93]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Road1"
            geometry={nodes.Road1.geometry}
            material={materials.road}
            castShadow
            receiveShadow
            position={[-205.55, -170.65, 0.93]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <group name="Room1" position={[369.06, 177.5, 200]}>
          <mesh
            name="ball"
            geometry={nodes.ball.geometry}
            material={materials.arrow}
            castShadow
            receiveShadow
            position={[5.94, -84.5, 17]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <group name="resume" position={[-75, 39.27, -175]}>
            <mesh
              name="Rectangle 2"
              geometry={nodes["Rectangle 2"].geometry}
              material={materials["Rectangle 2 Material"]}
              castShadow
              receiveShadow
              position={[0, -0.27, 1]}
            />
            <mesh
              name="Rectangle8"
              geometry={nodes.Rectangle8.geometry}
              material={materials.pot}
              castShadow
              receiveShadow
              position={[0, 0, -2]}
            />
          </group>
          <group name="carpet" position={[87.82, -154.45, 34]}>
            <mesh
              name="Ellipse 2"
              geometry={nodes["Ellipse 2"].geometry}
              material={materials.room1_floor}
              castShadow
              receiveShadow
              position={[0, 0.44, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Ellipse"
              geometry={nodes.Ellipse.geometry}
              material={materials.idk}
              castShadow
              receiveShadow
              position={[0, -1.44, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="plant" position={[-122.37, -105.03, -143.73]}>
            <mesh
              name="plant1"
              geometry={nodes.plant1.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[-5.54, -13.85, 10.56]}
              rotation={[-1.53, 0.07, 1.75]}
            />
            <mesh
              name="plant2"
              geometry={nodes.plant2.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[-2.01, -14.38, -3.72]}
              rotation={[-1.75, 0, -1.81]}
            />
            <mesh
              name="plant3"
              geometry={nodes.plant3.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[7.08, -12.64, 5.57]}
              rotation={[-Math.PI / 2, 0.1, -Math.PI]}
            />
            <mesh
              name="plant4"
              geometry={nodes.plant4.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[-7.68, -11.83, 5.57]}
              rotation={[-Math.PI / 2, -0.06, 0]}
            />
            <mesh
              name="pot"
              geometry={nodes.pot.geometry}
              material={materials.pot}
              castShadow
              receiveShadow
              position={[-2.55, -217.56, 3.63]}
            />
          </group>
          <group
            name="cv"
            position={[131, -89.95, 22.83]}
            rotation={[0, Math.PI / 4, 0]}
          >
            <mesh
              name="cv_ectangle"
              geometry={nodes.cv_ectangle.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[2.73, 4.61, 3.4]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="cv_rectangle 3"
              geometry={nodes["cv_rectangle 3"].geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-2.78, -3.02, 4.17]}
              rotation={[-Math.PI / 2, 0, -0.39]}
            />
            <mesh
              name="cv_rectangle 2"
              geometry={nodes["cv_rectangle 2"].geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-7.2, -0.06, -5.13]}
              rotation={[-Math.PI / 2, 0, -0.68]}
            />
          </group>
          <group
            name="controller"
            position={[55.57, -91.03, 7.95]}
            rotation={[0.09, 0, 0]}
            scale={1.66}
          >
            <mesh
              name="Ellipse 21"
              geometry={nodes["Ellipse 21"].geometry}
              material={materials["Ellipse 21 Material"]}
              castShadow
              receiveShadow
              position={[-1.79, 2.01, -0.79]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1.72}
            />
            <mesh
              name="Ellipse1"
              geometry={nodes.Ellipse1.geometry}
              material={materials["Ellipse1 Material"]}
              castShadow
              receiveShadow
              position={[1.81, 2.01, -0.79]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1.72}
            />
            <mesh
              name="Cube 3"
              geometry={nodes["Cube 3"].geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[6.11, 0.27, 0.82]}
              rotation={[-Math.PI / 2, 0, 2.18]}
              scale={0.62}
            />
            <mesh
              name="Cube 27"
              geometry={nodes["Cube 27"].geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-6.11, 0.27, 0.59]}
              rotation={[-Math.PI / 2, 0, 0.96]}
              scale={0.62}
            />
            <mesh
              name="Cube7"
              geometry={nodes.Cube7.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[-0.07, -0.01, -1.45]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="tv" position={[83.06, -63.48, 177.1]}>
            <mesh
              name="Triangle 3"
              geometry={nodes["Triangle 3"].geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[-11.8, -37.9, 0]}
              rotation={[Math.PI / 2, 1.22, -Math.PI / 2]}
            />
            <mesh
              name="Triangle 2"
              geometry={nodes["Triangle 2"].geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[9.25, -37.9, 0]}
              rotation={[-Math.PI / 2, 1.22, Math.PI / 2]}
            />
            <mesh
              name="Rectangle 21"
              geometry={nodes["Rectangle 21"].geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[0, 6.06, -1.42]}
            />
          </group>
          <group name="tv_table" position={[83, -131.7, 177.5]}>
            <mesh
              name="Cylinder 4"
              geometry={nodes["Cylinder 4"].geometry}
              material={materials["Cylinder 4 Material"]}
              castShadow
              receiveShadow
              position={[65.86, -13.89, 9.39]}
              rotation={[0, 0, 0.26]}
            />
            <mesh
              name="Cylinder 2"
              geometry={nodes["Cylinder 2"].geometry}
              material={materials["Cylinder 2 Material"]}
              castShadow
              receiveShadow
              position={[-65.57, -13.82, 9.39]}
              rotation={[0, 0, -0.26]}
            />
            <mesh
              name="Cylinder 3"
              geometry={nodes["Cylinder 3"].geometry}
              material={materials["Cylinder 3 Material"]}
              castShadow
              receiveShadow
              position={[66.08, -13.83, -9.5]}
              rotation={[0, 0, 0.26]}
            />
            <mesh
              name="Cylinder1"
              geometry={nodes.Cylinder1.geometry}
              material={materials["Cylinder1 Material"]}
              castShadow
              receiveShadow
              position={[-65.32, -13.89, -9.5]}
              rotation={[0, 0, -0.26]}
            />
            <mesh
              name="Rectangle9"
              geometry={nodes.Rectangle9.geometry}
              material={materials.piano_chair_leg}
              castShadow
              receiveShadow
              position={[0, -4.44, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="tabel" position={[76.5, -124.59, 13.3]}>
            <mesh
              name="leg_1 2"
              geometry={nodes["leg_1 2"].geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-84.73, -5.23, 33.5]}
            />
            <mesh
              name="leg_1"
              geometry={nodes.leg_1.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[87.44, -5.23, 33.5]}
            />
            <mesh
              name="leg_3"
              geometry={nodes.leg_3.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[87.44, -5.23, -32.5]}
            />
            <mesh
              name="leg_4"
              geometry={nodes.leg_4.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-85, -5.23, -32.5]}
            />
            <mesh
              name="top"
              geometry={nodes.top.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[0, 18.38, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="piano_chair" position={[-110.07, -137.3, 84.52]}>
            <mesh
              name="Cube8"
              geometry={nodes.Cube8.geometry}
              material={materials["Cube8 Material"]}
              castShadow
              receiveShadow
              position={[0, 14.32, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cylinder2"
              geometry={nodes.Cylinder2.geometry}
              material={materials.piano_chair_leg}
              castShadow
              receiveShadow
              position={[-11.85, -3.32, -11.89]}
            />
          </group>
          <group name="piano" position={[-144.75, -94.21, 153.21]}>
            <mesh
              name="black_keys"
              geometry={nodes.black_keys.geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[1.35, 18.46, -12.82]}
            />
            <mesh
              name="white_keys"
              geometry={nodes.white_keys.geometry}
              material={materials.piano_key_white}
              castShadow
              receiveShadow
              position={[3.94, 16.97, -4.22]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1, 1.07, 1]}
            />
            <mesh
              name="under_key"
              geometry={nodes.under_key.geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[5.95, 14.45, -69.77]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="top_body"
              geometry={nodes.top_body.geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[-14.66, 46.46, -68.24]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="back"
              geometry={nodes.back.geometry}
              material={materials.piano_body}
              castShadow
              receiveShadow
              position={[-20.82, -0.26, -68.98]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <group name="right leg" position={[0, 0, -139.15]}>
              <mesh
                name="Cube 4"
                geometry={nodes["Cube 4"].geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[-12.24, 0, 0.73]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Cube 31"
                geometry={nodes["Cube 31"].geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[8.75, -53.87, 0.73]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Cube 28"
                geometry={nodes["Cube 28"].geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[12.16, 14.95, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Cube9"
                geometry={nodes.Cube9.geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[19.82, -26.22, 0.97]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="left lef">
              <mesh
                name="Cube 41"
                geometry={nodes["Cube 41"].geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[-12.24, 0, 0.73]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Cube 32"
                geometry={nodes["Cube 32"].geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[8.75, -53.87, 0.73]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Cube 29"
                geometry={nodes["Cube 29"].geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[12.16, 14.95, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Cube10"
                geometry={nodes.Cube10.geometry}
                material={materials.piano_body}
                castShadow
                receiveShadow
                position={[19.82, -26.22, 0.97]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
          </group>
          <group name="sofa" position={[107.72, -94.77, -126.56]}>
            <mesh
              name="Cube 42"
              geometry={nodes["Cube 42"].geometry}
              material={materials.sofa}
              castShadow
              receiveShadow
              position={[0.5, 20.33, -36.5]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube 33"
              geometry={nodes["Cube 33"].geometry}
              material={materials.sofa}
              castShadow
              receiveShadow
              position={[0, -20.27, 0]}
            />
            <mesh
              name="Cube 210"
              geometry={nodes["Cube 210"].geometry}
              material={materials.sofa}
              castShadow
              receiveShadow
              position={[0, -46.51, 0]}
            />
          </group>
          <group name="linkedin" position={[101.41, 42.28, -124]} scale={0.1}>
            <mesh
              name="Merged Geometry"
              geometry={nodes["Merged Geometry"].geometry}
              material={materials["Merged Geometry Material"]}
              receiveShadow
              position={[-10.75, 3.5, -511]}
            />
            <mesh
              name="Rectangle10"
              geometry={nodes.Rectangle10.geometry}
              material={materials["Rectangle10 Material"]}
              castShadow
              receiveShadow
              position={[-10.69, 0, -532.64]}
            />
          </group>
          <mesh
            name="wall_right"
            geometry={nodes.wall_right.geometry}
            material={materials.room1_floor}
            castShadow
            receiveShadow
            position={[0, 2.5, -200]}
          />
          <group name="windows frame" position={[-175.5, 55.45, -41.52]}>
            <mesh
              name="Rectangle 3"
              geometry={nodes["Rectangle 3"].geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-1.5, 2.62, -53.29]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 22"
              geometry={nodes["Rectangle 22"].geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-1.5, 2.33, 53.29]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 5"
              geometry={nodes["Rectangle 5"].geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-1.5, -23.6, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 4"
              geometry={nodes["Rectangle 4"].geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-1.5, -69.05, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle11"
              geometry={nodes.Rectangle11.geometry}
              material={materials["table _brown"]}
              castShadow
              receiveShadow
              position={[-1.5, 69.05, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
          </group>
          <mesh
            name="window"
            geometry={nodes.window.geometry}
            material={materials.room1_floor}
            castShadow
            receiveShadow
            position={[-189, 2.5, 0]}
          >
            <mesh
              name="Cube11"
              geometry={nodes.Cube11.geometry}
              material={materials["Cube11 Material"]}
              visible={false}
              castShadow
              receiveShadow
              position={[0.08, 52.33, -41.52]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="wall_left"
              geometry={nodes.wall_left.geometry}
              material={materials.room1_floor}
              visible={false}
              castShadow
              receiveShadow
              position={[-11, 0, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
          </mesh>
          <mesh
            name="floor"
            geometry={nodes.floor.geometry}
            material={materials.room1_floor}
            castShadow
            receiveShadow
            position={[0, -177.5, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <pointLight
          name="Point Light"
          castShadow
          intensity={1}
          distance={2000}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={100}
          shadow-camera-far={100000}
          position={[760.12, 981.41, 302.19]}
        />
        <mesh
          name="ground"
          geometry={nodes.ground.geometry}
          material={materials["ground Material"]}
          castShadow
          receiveShadow
          position={[4, 1, -4]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <OrthographicCamera
          name="Camera"
          makeDefault={true}
          zoom={1.85}
          far={100000}
          near={-100000}
          up={[0, 1, 0]}
          position={[883.96, 643.63, 689.92]}
          rotation={[-Math.PI / 4, 0.62, Math.PI / 6]}
        />
        <hemisphereLight
          name="Default Ambient Light"
          intensity={0.75}
          color="#eaeaea"
          position={[0, 1, 0]}
        />
      </group>
    </>
  );
}
